version: "3"
services:
  lock-server:
    volumes:
      - '.:/Users/Darragh/College/ScalableComputing/py_dfs/distibuted-file-system/lock-server/'
    build: .
    environment:
          - SERVER_IP=192.168.0.25
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "7000:80"