version: "3"
services:
  file_server1:
    volumes:
      # Switch to separate folders per server
      - '.:/Users/Darragh/College/ScalableComputing/py_dfs/distibuted-file-system/file-server/'
    build: .
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "9000:80"
  file_server2:
    volumes:
      - '.:/Users/Darragh/College/ScalableComputing/py_dfs/distibuted-file-system/file-server/'
    build: .
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "9001:80"