version: "3"
services:
  directory-server:
    volumes:
      - '.:/Users/Darragh/College/ScalableComputing/py_dfs/distibuted-file-system/directory-server/'
    build: .
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8001:80"